version: "3.7"

services:
  app:
    image: git-kanban/node:v3
    build: .
    command: npm run start:nodemon
    working_dir: /app
    ports:
      - 80:3000
    volumes:
      - .:/app
    restart: unless-stopped
