version: "3.7"

services:
  app:
    image: git-kanban/node:v3
    build: .
    command: npm run start:nodemon
    working_dir: /app
    ports:
      - "80:3000"
    volumes:
      - .:/app
    restart: unless-stopped
  redis:
    image: redis:5-alpine
    ports:
      - "6379:6379"
    volumes:
      - .docker/data/redis:/data
    restart: unless-stopped
  redis_commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8888:8081
    depends_on:
      - redis
    restart: unless-stopped
